name: alert_to_divert
description: Thesis app — login/signup with Supabase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  path: ^1.8.3
  
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  geolocator: ^10.1.0
  permission_handler: ^11.3.0
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.jpg
    - .env
